<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Geolocation\City;
use App\Models\Geolocation\State;
class CitiesSeeder extends Seeder
{
     /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ['state'=>'5','name'=>'Medellín','code'=>'5,001'],
            ['state'=>'5','name'=>'Abejorral','code'=>'5,002'],
            ['state'=>'5','name'=>'Abriaquí','code'=>'5,004'],
            ['state'=>'5','name'=>'Alejandría','code'=>'5,021'],
            ['state'=>'5','name'=>'Amagá','code'=>'5,03'],
            ['state'=>'5','name'=>'Amalfi','code'=>'5,031'],
            ['state'=>'5','name'=>'Andes','code'=>'5,034'],
            ['state'=>'5','name'=>'Angelópolis','code'=>'5,036'],
            ['state'=>'5','name'=>'Angostura','code'=>'5,038'],
            ['state'=>'5','name'=>'Anorí','code'=>'5,04'],
            ['state'=>'68','name'=>'Chimá','code'=>'68,176'],
            ['state'=>'5','name'=>'Anza','code'=>'5,044'],
            ['state'=>'5','name'=>'Apartadó','code'=>'5,045'],
            ['state'=>'5','name'=>'Arboletes','code'=>'5,051'],
            ['state'=>'5','name'=>'Argelia','code'=>'5,055'],
            ['state'=>'5','name'=>'Armenia','code'=>'5,059'],
            ['state'=>'5','name'=>'Barbosa','code'=>'5,079'],
            ['state'=>'5','name'=>'Bello','code'=>'5,088'],
            ['state'=>'5','name'=>'Betania','code'=>'5,091'],
            ['state'=>'5','name'=>'Betulia','code'=>'5,093'],
            ['state'=>'5','name'=>'Ciudad Bolívar','code'=>'5,101'],
            ['state'=>'5','name'=>'Briceño','code'=>'5,107'],
            ['state'=>'5','name'=>'Buriticá','code'=>'5,113'],
            ['state'=>'5','name'=>'Cáceres','code'=>'5,12'],
            ['state'=>'5','name'=>'Caicedo','code'=>'5,125'],
            ['state'=>'5','name'=>'Caldas','code'=>'5,129'],
            ['state'=>'5','name'=>'Campamento','code'=>'5,134'],
            ['state'=>'5','name'=>'Cañasgordas','code'=>'5,138'],
            ['state'=>'5','name'=>'Caracolí','code'=>'5,142'],
            ['state'=>'5','name'=>'Caramanta','code'=>'5,145'],
            ['state'=>'5','name'=>'Carepa','code'=>'5,147'],
            ['state'=>'70','name'=>'Sampués','code'=>'70,67'],
            ['state'=>'5','name'=>'Carolina','code'=>'5,15'],
            ['state'=>'5','name'=>'Caucasia','code'=>'5,154'],
            ['state'=>'5','name'=>'Chigorodó','code'=>'5,172'],
            ['state'=>'5','name'=>'Cisneros','code'=>'5,19'],
            ['state'=>'5','name'=>'Cocorná','code'=>'5,197'],
            ['state'=>'5','name'=>'Concepción','code'=>'5,206'],
            ['state'=>'5','name'=>'Concordia','code'=>'5,209'],
            ['state'=>'5','name'=>'Copacabana','code'=>'5,212'],
            ['state'=>'5','name'=>'Dabeiba','code'=>'5,234'],
            ['state'=>'5','name'=>'Don Matías','code'=>'5,237'],
            ['state'=>'5','name'=>'Ebéjico','code'=>'5,24'],
            ['state'=>'5','name'=>'El Bagre','code'=>'5,25'],
            ['state'=>'5','name'=>'Entrerrios','code'=>'5,264'],
            ['state'=>'5','name'=>'Envigado','code'=>'5,266'],
            ['state'=>'5','name'=>'Fredonia','code'=>'5,282'],
            ['state'=>'5','name'=>'Giraldo','code'=>'5,306'],
            ['state'=>'5','name'=>'Girardota','code'=>'5,308'],
            ['state'=>'5','name'=>'Gómez Plata','code'=>'5,31'],
            ['state'=>'85','name'=>'Nunchía','code'=>'85,225'],
            ['state'=>'5','name'=>'Guadalupe','code'=>'5,315'],
            ['state'=>'5','name'=>'Guarne','code'=>'5,318'],
            ['state'=>'5','name'=>'Guatapé','code'=>'5,321'],
            ['state'=>'5','name'=>'Heliconia','code'=>'5,347'],
            ['state'=>'5','name'=>'Hispania','code'=>'5,353'],
            ['state'=>'5','name'=>'Itagui','code'=>'5,36'],
            ['state'=>'5','name'=>'Ituango','code'=>'5,361'],
            ['state'=>'54','name'=>'Pamplona','code'=>'54,518'],
            ['state'=>'5','name'=>'Jericó','code'=>'5,368'],
            ['state'=>'5','name'=>'La Ceja','code'=>'5,376'],
            ['state'=>'5','name'=>'La Estrella','code'=>'5,38'],
            ['state'=>'5','name'=>'La Pintada','code'=>'5,39'],
            ['state'=>'5','name'=>'La Unión','code'=>'5,4'],
            ['state'=>'5','name'=>'Liborina','code'=>'5,411'],
            ['state'=>'5','name'=>'Maceo','code'=>'5,425'],
            ['state'=>'5','name'=>'Marinilla','code'=>'5,44'],
            ['state'=>'5','name'=>'Montebello','code'=>'5,467'],
            ['state'=>'5','name'=>'Murindó','code'=>'5,475'],
            ['state'=>'5','name'=>'Mutatá','code'=>'5,48'],
            ['state'=>'5','name'=>'Nariño','code'=>'5,483'],
            ['state'=>'5','name'=>'Necoclí','code'=>'5,49'],
            ['state'=>'5','name'=>'Nechí','code'=>'5,495'],
            ['state'=>'5','name'=>'Olaya','code'=>'5,501'],
            ['state'=>'5','name'=>'Peñol','code'=>'5,541'],
            ['state'=>'5','name'=>'Peque','code'=>'5,543'],
            ['state'=>'5','name'=>'Pueblorrico','code'=>'5,576'],
            ['state'=>'5','name'=>'Puerto Berrío','code'=>'5,579'],
            ['state'=>'5','name'=>'Puerto Nare','code'=>'5,585'],
            ['state'=>'5','name'=>'Puerto Triunfo','code'=>'5,591'],
            ['state'=>'5','name'=>'Remedios','code'=>'5,604'],
            ['state'=>'5','name'=>'Retiro','code'=>'5,607'],
            ['state'=>'5','name'=>'Rionegro','code'=>'5,615'],
            ['state'=>'5','name'=>'Sabanalarga','code'=>'5,628'],
            ['state'=>'5','name'=>'Sabaneta','code'=>'5,631'],
            ['state'=>'5','name'=>'Salgar','code'=>'5,642'],
            ['state'=>'25','name'=>'Albán','code'=>'25,019'],
            ['state'=>'97','name'=>'Yavaraté','code'=>'97,889'],
            ['state'=>'5','name'=>'San Francisco','code'=>'5,652'],
            ['state'=>'5','name'=>'San Jerónimo','code'=>'5,656'],
            ['state'=>'23','name'=>'Montelíbano','code'=>'23,466'],
            ['state'=>'86','name'=>'Puerto Asís','code'=>'86,568'],
            ['state'=>'5','name'=>'San Luis','code'=>'5,66'],
            ['state'=>'5','name'=>'San Pedro','code'=>'5,664'],
            ['state'=>'70','name'=>'Corozal','code'=>'70,215'],
            ['state'=>'5','name'=>'San Rafael','code'=>'5,667'],
            ['state'=>'5','name'=>'San Roque','code'=>'5,67'],
            ['state'=>'5','name'=>'San Vicente','code'=>'5,674'],
            ['state'=>'5','name'=>'Santa Bárbara','code'=>'5,679'],
            ['state'=>'52','name'=>'Buesaco','code'=>'52,11'],
            ['state'=>'5','name'=>'Santo Domingo','code'=>'5,69'],
            ['state'=>'5','name'=>'El Santuario','code'=>'5,697'],
            ['state'=>'5','name'=>'Segovia','code'=>'5,736'],
            ['state'=>'5','name'=>'Sopetrán','code'=>'5,761'],
            ['state'=>'5','name'=>'Támesis','code'=>'5,789'],
            ['state'=>'5','name'=>'Tarazá','code'=>'5,79'],
            ['state'=>'5','name'=>'Tarso','code'=>'5,792'],
            ['state'=>'5','name'=>'Titiribí','code'=>'5,809'],
            ['state'=>'5','name'=>'Toledo','code'=>'5,819'],
            ['state'=>'5','name'=>'Turbo','code'=>'5,837'],
            ['state'=>'5','name'=>'Uramita','code'=>'5,842'],
            ['state'=>'5','name'=>'Urrao','code'=>'5,847'],
            ['state'=>'5','name'=>'Valdivia','code'=>'5,854'],
            ['state'=>'5','name'=>'Valparaíso','code'=>'5,856'],
            ['state'=>'5','name'=>'Vegachí','code'=>'5,858'],
            ['state'=>'5','name'=>'Venecia','code'=>'5,861'],
            ['state'=>'85','name'=>'Maní','code'=>'85,139'],
            ['state'=>'5','name'=>'Yalí','code'=>'5,885'],
            ['state'=>'5','name'=>'Yarumal','code'=>'5,887'],
            ['state'=>'5','name'=>'Yolombó','code'=>'5,89'],
            ['state'=>'5','name'=>'Yondó','code'=>'5,893'],
            ['state'=>'5','name'=>'Zaragoza','code'=>'5,895'],
            ['state'=>'8','name'=>'Barranquilla','code'=>'8,001'],
            ['state'=>'8','name'=>'Baranoa','code'=>'8,078'],
            ['state'=>'13','name'=>'El Peñón','code'=>'13,268'],
            ['state'=>'8','name'=>'Candelaria','code'=>'8,141'],
            ['state'=>'8','name'=>'Galapa','code'=>'8,296'],
            ['state'=>'76','name'=>'Tuluá','code'=>'76,834'],
            ['state'=>'73','name'=>'Casabianca','code'=>'73,152'],
            ['state'=>'8','name'=>'Luruaco','code'=>'8,421'],
            ['state'=>'8','name'=>'Malambo','code'=>'8,433'],
            ['state'=>'8','name'=>'Manatí','code'=>'8,436'],
            ['state'=>'25','name'=>'Anolaima','code'=>'25,04'],
            ['state'=>'8','name'=>'Piojó','code'=>'8,549'],
            ['state'=>'8','name'=>'Polonuevo','code'=>'8,558'],
            ['state'=>'25','name'=>'Chía','code'=>'25,175'],
            ['state'=>'52','name'=>'San Andrés de Tumaco','code'=>'52,835'],
            ['state'=>'8','name'=>'Sabanagrande','code'=>'8,634'],
            ['state'=>'8','name'=>'Sabanalarga','code'=>'8,638'],
            ['state'=>'8','name'=>'Santa Lucía','code'=>'8,675'],
            ['state'=>'8','name'=>'Santo Tomás','code'=>'8,685'],
            ['state'=>'8','name'=>'Soledad','code'=>'8,758'],
            ['state'=>'8','name'=>'Suan','code'=>'8,77'],
            ['state'=>'8','name'=>'Tubará','code'=>'8,832'],
            ['state'=>'8','name'=>'Usiacurí','code'=>'8,849'],
            ['state'=>'18','name'=>'Milán','code'=>'18,46'],
            ['state'=>'68','name'=>'Capitanejo','code'=>'68,147'],
            ['state'=>'13','name'=>'Achí','code'=>'13,006'],
            ['state'=>'73','name'=>'Anzoátegui','code'=>'73,043'],
            ['state'=>'13','name'=>'Arenal','code'=>'13,042'],
            ['state'=>'13','name'=>'Arjona','code'=>'13,052'],
            ['state'=>'13','name'=>'Arroyohondo','code'=>'13,062'],
            ['state'=>'76','name'=>'Florida','code'=>'76,275'],
            ['state'=>'13','name'=>'Calamar','code'=>'13,14'],
            ['state'=>'13','name'=>'Cantagallo','code'=>'13,16'],
            ['state'=>'13','name'=>'Cicuco','code'=>'13,188'],
            ['state'=>'13','name'=>'Córdoba','code'=>'13,212'],
            ['state'=>'13','name'=>'Clemencia','code'=>'13,222'],
            ['state'=>'8','name'=>'Repelón','code'=>'8,606'],
            ['state'=>'13','name'=>'El Guamo','code'=>'13,248'],
            ['state'=>'5','name'=>'Frontino','code'=>'5,284'],
            ['state'=>'13','name'=>'Magangué','code'=>'13,43'],
            ['state'=>'13','name'=>'Mahates','code'=>'13,433'],
            ['state'=>'13','name'=>'Margarita','code'=>'13,44'],
            ['state'=>'13','name'=>'Montecristo','code'=>'13,458'],
            ['state'=>'13','name'=>'Mompós','code'=>'13,468'],
            ['state'=>'13','name'=>'Morales','code'=>'13,473'],
            ['state'=>'13','name'=>'Norosí','code'=>'13,49'],
            ['state'=>'13','name'=>'Pinillos','code'=>'13,549'],
            ['state'=>'13','name'=>'Regidor','code'=>'13,58'],
            ['state'=>'13','name'=>'Río Viejo','code'=>'13,6'],
            ['state'=>'13','name'=>'San Estanislao','code'=>'13,647'],
            ['state'=>'13','name'=>'San Fernando','code'=>'13,65'],
            ['state'=>'25','name'=>'El Peñón','code'=>'25,258'],
            ['state'=>'54','name'=>'Pamplonita','code'=>'54,52'],
            ['state'=>'13','name'=>'San Juan Nepomuceno','code'=>'13,657'],
            ['state'=>'91','name'=>'Miriti Paraná','code'=>'91,46'],
            ['state'=>'85','name'=>'Támara','code'=>'85,4'],
            ['state'=>'13','name'=>'Santa Catalina','code'=>'13,673'],
            ['state'=>'13','name'=>'Santa Rosa','code'=>'13,683'],
            ['state'=>'15','name'=>'Tibasosa','code'=>'15,806'],
            ['state'=>'13','name'=>'Simití','code'=>'13,744'],
            ['state'=>'13','name'=>'Soplaviento','code'=>'13,76'],
            ['state'=>'13','name'=>'Talaigua Nuevo','code'=>'13,78'],
            ['state'=>'13','name'=>'Tiquisio','code'=>'13,81'],
            ['state'=>'13','name'=>'Turbaco','code'=>'13,836'],
            ['state'=>'13','name'=>'Turbaná','code'=>'13,838'],
            ['state'=>'13','name'=>'Villanueva','code'=>'13,873'],
            ['state'=>'19','name'=>'Páez','code'=>'19,517'],
            ['state'=>'15','name'=>'Tunja','code'=>'15,001'],
            ['state'=>'15','name'=>'Almeida','code'=>'15,022'],
            ['state'=>'15','name'=>'Aquitania','code'=>'15,047'],
            ['state'=>'15','name'=>'Arcabuco','code'=>'15,051'],
            ['state'=>'73','name'=>'Ibagué','code'=>'73,001'],
            ['state'=>'15','name'=>'Berbeo','code'=>'15,09'],
            ['state'=>'15','name'=>'Betéitiva','code'=>'15,092'],
            ['state'=>'15','name'=>'Boavita','code'=>'15,097'],
            ['state'=>'15','name'=>'Boyacá','code'=>'15,104'],
            ['state'=>'15','name'=>'Briceño','code'=>'15,106'],
            ['state'=>'15','name'=>'Buena Vista','code'=>'15,109'],
            ['state'=>'15','name'=>'Busbanzá','code'=>'15,114'],
            ['state'=>'15','name'=>'Caldas','code'=>'15,131'],
            ['state'=>'15','name'=>'Campohermoso','code'=>'15,135'],
            ['state'=>'15','name'=>'Cerinza','code'=>'15,162'],
            ['state'=>'15','name'=>'Chinavita','code'=>'15,172'],
            ['state'=>'15','name'=>'Chiquinquirá','code'=>'15,176'],
            ['state'=>'15','name'=>'Chiscas','code'=>'15,18'],
            ['state'=>'15','name'=>'Chita','code'=>'15,183'],
            ['state'=>'15','name'=>'Chitaraque','code'=>'15,185'],
            ['state'=>'15','name'=>'Chivatá','code'=>'15,187'],
            ['state'=>'15','name'=>'Cómbita','code'=>'15,204'],
            ['state'=>'15','name'=>'Coper','code'=>'15,212'],
            ['state'=>'15','name'=>'Corrales','code'=>'15,215'],
            ['state'=>'15','name'=>'Covarachía','code'=>'15,218'],
            ['state'=>'15','name'=>'Cubará','code'=>'15,223'],
            ['state'=>'15','name'=>'Cucaita','code'=>'15,224'],
            ['state'=>'15','name'=>'Cuítiva','code'=>'15,226'],
            ['state'=>'15','name'=>'Chíquiza','code'=>'15,232'],
            ['state'=>'15','name'=>'Chivor','code'=>'15,236'],
            ['state'=>'15','name'=>'Duitama','code'=>'15,238'],
            ['state'=>'15','name'=>'El Cocuy','code'=>'15,244'],
            ['state'=>'15','name'=>'El Espino','code'=>'15,248'],
            ['state'=>'15','name'=>'Firavitoba','code'=>'15,272'],
            ['state'=>'15','name'=>'Floresta','code'=>'15,276'],
            ['state'=>'15','name'=>'Gachantivá','code'=>'15,293'],
            ['state'=>'15','name'=>'Gameza','code'=>'15,296'],
            ['state'=>'15','name'=>'Garagoa','code'=>'15,299'],
            ['state'=>'15','name'=>'Guacamayas','code'=>'15,317'],
            ['state'=>'15','name'=>'Guateque','code'=>'15,322'],
            ['state'=>'15','name'=>'Guayatá','code'=>'15,325'],
            ['state'=>'15','name'=>'Güicán','code'=>'15,332'],
            ['state'=>'15','name'=>'Iza','code'=>'15,362'],
            ['state'=>'15','name'=>'Jenesano','code'=>'15,367'],
            ['state'=>'15','name'=>'Jericó','code'=>'15,368'],
            ['state'=>'15','name'=>'Labranzagrande','code'=>'15,377'],
            ['state'=>'15','name'=>'La Capilla','code'=>'15,38'],
            ['state'=>'15','name'=>'La Victoria','code'=>'15,401'],
            ['state'=>'8','name'=>'Puerto Colombia','code'=>'8,573'],
            ['state'=>'52','name'=>'Belén','code'=>'52,083'],
            ['state'=>'15','name'=>'Macanal','code'=>'15,425'],
            ['state'=>'15','name'=>'Maripí','code'=>'15,442'],
            ['state'=>'15','name'=>'Miraflores','code'=>'15,455'],
            ['state'=>'15','name'=>'Mongua','code'=>'15,464'],
            ['state'=>'15','name'=>'Monguí','code'=>'15,466'],
            ['state'=>'15','name'=>'Moniquirá','code'=>'15,469'],
            ['state'=>'15','name'=>'Muzo','code'=>'15,48'],
            ['state'=>'15','name'=>'Nobsa','code'=>'15,491'],
            ['state'=>'15','name'=>'Nuevo Colón','code'=>'15,494'],
            ['state'=>'15','name'=>'Oicatá','code'=>'15,5'],
            ['state'=>'15','name'=>'Otanche','code'=>'15,507'],
            ['state'=>'15','name'=>'Pachavita','code'=>'15,511'],
            ['state'=>'15','name'=>'Páez','code'=>'15,514'],
            ['state'=>'15','name'=>'Paipa','code'=>'15,516'],
            ['state'=>'15','name'=>'Pajarito','code'=>'15,518'],
            ['state'=>'15','name'=>'Panqueba','code'=>'15,522'],
            ['state'=>'15','name'=>'Pauna','code'=>'15,531'],
            ['state'=>'15','name'=>'Paya','code'=>'15,533'],
            ['state'=>'25','name'=>'Sopó','code'=>'25,758'],
            ['state'=>'15','name'=>'Pesca','code'=>'15,542'],
            ['state'=>'15','name'=>'Pisba','code'=>'15,55'],
            ['state'=>'15','name'=>'Puerto Boyacá','code'=>'15,572'],
            ['state'=>'15','name'=>'Quípama','code'=>'15,58'],
            ['state'=>'15','name'=>'Ramiriquí','code'=>'15,599'],
            ['state'=>'15','name'=>'Ráquira','code'=>'15,6'],
            ['state'=>'15','name'=>'Rondón','code'=>'15,621'],
            ['state'=>'15','name'=>'Saboyá','code'=>'15,632'],
            ['state'=>'15','name'=>'Sáchica','code'=>'15,638'],
            ['state'=>'15','name'=>'Samacá','code'=>'15,646'],
            ['state'=>'15','name'=>'San Eduardo','code'=>'15,66'],
            ['state'=>'27','name'=>'Carmen del Darien','code'=>'27,15'],
            ['state'=>'25','name'=>'Gama','code'=>'25,299'],
            ['state'=>'15','name'=>'San Mateo','code'=>'15,673'],
            ['state'=>'25','name'=>'Sasaima','code'=>'25,718'],
            ['state'=>'52','name'=>'Chachagüí','code'=>'52,24'],
            ['state'=>'15','name'=>'Santana','code'=>'15,686'],
            ['state'=>'15','name'=>'Santa María','code'=>'15,69'],
            ['state'=>'54','name'=>'Cúcuta','code'=>'54,001'],
            ['state'=>'15','name'=>'Santa Sofía','code'=>'15,696'],
            ['state'=>'15','name'=>'Sativanorte','code'=>'15,72'],
            ['state'=>'15','name'=>'Sativasur','code'=>'15,723'],
            ['state'=>'15','name'=>'Siachoque','code'=>'15,74'],
            ['state'=>'15','name'=>'Soatá','code'=>'15,753'],
            ['state'=>'15','name'=>'Socotá','code'=>'15,755'],
            ['state'=>'15','name'=>'Socha','code'=>'15,757'],
            ['state'=>'15','name'=>'Sogamoso','code'=>'15,759'],
            ['state'=>'15','name'=>'Somondoco','code'=>'15,761'],
            ['state'=>'15','name'=>'Sora','code'=>'15,762'],
            ['state'=>'15','name'=>'Sotaquirá','code'=>'15,763'],
            ['state'=>'15','name'=>'Soracá','code'=>'15,764'],
            ['state'=>'15','name'=>'Susacón','code'=>'15,774'],
            ['state'=>'15','name'=>'Sutamarchán','code'=>'15,776'],
            ['state'=>'15','name'=>'Sutatenza','code'=>'15,778'],
            ['state'=>'15','name'=>'Tasco','code'=>'15,79'],
            ['state'=>'15','name'=>'Tenza','code'=>'15,798'],
            ['state'=>'15','name'=>'Tibaná','code'=>'15,804'],
            ['state'=>'15','name'=>'Tinjacá','code'=>'15,808'],
            ['state'=>'15','name'=>'Tipacoque','code'=>'15,81'],
            ['state'=>'15','name'=>'Toca','code'=>'15,814'],
            ['state'=>'13','name'=>'Cartagena','code'=>'13,001'],
            ['state'=>'15','name'=>'Tópaga','code'=>'15,82'],
            ['state'=>'15','name'=>'Tota','code'=>'15,822'],
            ['state'=>'15','name'=>'Turmequé','code'=>'15,835'],
            ['state'=>'5','name'=>'Granada','code'=>'5,313'],
            ['state'=>'15','name'=>'Tutazá','code'=>'15,839'],
            ['state'=>'15','name'=>'Umbita','code'=>'15,842'],
            ['state'=>'15','name'=>'Ventaquemada','code'=>'15,861'],
            ['state'=>'15','name'=>'Viracachá','code'=>'15,879'],
            ['state'=>'15','name'=>'Zetaquira','code'=>'15,897'],
            ['state'=>'17','name'=>'Manizales','code'=>'17,001'],
            ['state'=>'17','name'=>'Aguadas','code'=>'17,013'],
            ['state'=>'17','name'=>'Anserma','code'=>'17,042'],
            ['state'=>'17','name'=>'Aranzazu','code'=>'17,05'],
            ['state'=>'17','name'=>'Belalcázar','code'=>'17,088'],
            ['state'=>'17','name'=>'Chinchiná','code'=>'17,174'],
            ['state'=>'17','name'=>'Filadelfia','code'=>'17,272'],
            ['state'=>'17','name'=>'La Dorada','code'=>'17,38'],
            ['state'=>'17','name'=>'La Merced','code'=>'17,388'],
            ['state'=>'17','name'=>'Manzanares','code'=>'17,433'],
            ['state'=>'17','name'=>'Marmato','code'=>'17,442'],
            ['state'=>'17','name'=>'Marulanda','code'=>'17,446'],
            ['state'=>'17','name'=>'Neira','code'=>'17,486'],
            ['state'=>'17','name'=>'Norcasia','code'=>'17,495'],
            ['state'=>'17','name'=>'Pácora','code'=>'17,513'],
            ['state'=>'17','name'=>'Palestina','code'=>'17,524'],
            ['state'=>'17','name'=>'Pensilvania','code'=>'17,541'],
            ['state'=>'17','name'=>'Riosucio','code'=>'17,614'],
            ['state'=>'17','name'=>'Risaralda','code'=>'17,616'],
            ['state'=>'17','name'=>'Salamina','code'=>'17,653'],
            ['state'=>'17','name'=>'Samaná','code'=>'17,662'],
            ['state'=>'17','name'=>'San José','code'=>'17,665'],
            ['state'=>'17','name'=>'Supía','code'=>'17,777'],
            ['state'=>'17','name'=>'Victoria','code'=>'17,867'],
            ['state'=>'17','name'=>'Villamaría','code'=>'17,873'],
            ['state'=>'17','name'=>'Viterbo','code'=>'17,877'],
            ['state'=>'18','name'=>'Florencia','code'=>'18,001'],
            ['state'=>'18','name'=>'Albania','code'=>'18,029'],
            ['state'=>'47','name'=>'Santa Bárbara de Pinto','code'=>'47,72'],
            ['state'=>'13','name'=>'María la Baja','code'=>'13,442'],
            ['state'=>'18','name'=>'Curillo','code'=>'18,205'],
            ['state'=>'18','name'=>'El Doncello','code'=>'18,247'],
            ['state'=>'18','name'=>'El Paujil','code'=>'18,256'],
            ['state'=>'18','name'=>'Morelia','code'=>'18,479'],
            ['state'=>'18','name'=>'Puerto Rico','code'=>'18,592'],
            ['state'=>'18','name'=>'La Montañita','code'=>'18,41'],
            ['state'=>'18','name'=>'San Vicente del Caguán','code'=>'18,753'],
            ['state'=>'18','name'=>'Solano','code'=>'18,756'],
            ['state'=>'18','name'=>'Solita','code'=>'18,785'],
            ['state'=>'18','name'=>'Valparaíso','code'=>'18,86'],
            ['state'=>'19','name'=>'Popayán','code'=>'19,001'],
            ['state'=>'19','name'=>'Almaguer','code'=>'19,022'],
            ['state'=>'19','name'=>'Argelia','code'=>'19,05'],
            ['state'=>'19','name'=>'Balboa','code'=>'19,075'],
            ['state'=>'19','name'=>'Bolívar','code'=>'19,1'],
            ['state'=>'19','name'=>'Buenos Aires','code'=>'19,11'],
            ['state'=>'19','name'=>'Cajibío','code'=>'19,13'],
            ['state'=>'19','name'=>'Caldono','code'=>'19,137'],
            ['state'=>'19','name'=>'Caloto','code'=>'19,142'],
            ['state'=>'19','name'=>'Corinto','code'=>'19,212'],
            ['state'=>'19','name'=>'El Tambo','code'=>'19,256'],
            ['state'=>'19','name'=>'Florencia','code'=>'19,29'],
            ['state'=>'19','name'=>'Guachené','code'=>'19,3'],
            ['state'=>'19','name'=>'Guapi','code'=>'19,318'],
            ['state'=>'19','name'=>'Inzá','code'=>'19,355'],
            ['state'=>'19','name'=>'Jambaló','code'=>'19,364'],
            ['state'=>'19','name'=>'La Sierra','code'=>'19,392'],
            ['state'=>'19','name'=>'La Vega','code'=>'19,397'],
            ['state'=>'19','name'=>'López','code'=>'19,418'],
            ['state'=>'19','name'=>'Mercaderes','code'=>'19,45'],
            ['state'=>'19','name'=>'Miranda','code'=>'19,455'],
            ['state'=>'19','name'=>'Morales','code'=>'19,473'],
            ['state'=>'19','name'=>'Padilla','code'=>'19,513'],
            ['state'=>'19','name'=>'Patía','code'=>'19,532'],
            ['state'=>'19','name'=>'Piamonte','code'=>'19,533'],
            ['state'=>'19','name'=>'Piendamó','code'=>'19,548'],
            ['state'=>'19','name'=>'Puerto Tejada','code'=>'19,573'],
            ['state'=>'19','name'=>'Puracé','code'=>'19,585'],
            ['state'=>'19','name'=>'Rosas','code'=>'19,622'],
            ['state'=>'68','name'=>'El Peñón','code'=>'68,25'],
            ['state'=>'5','name'=>'Jardín','code'=>'5,364'],
            ['state'=>'19','name'=>'Santa Rosa','code'=>'19,701'],
            ['state'=>'19','name'=>'Silvia','code'=>'19,743'],
            ['state'=>'19','name'=>'Sotara','code'=>'19,76'],
            ['state'=>'19','name'=>'Suárez','code'=>'19,78'],
            ['state'=>'19','name'=>'Sucre','code'=>'19,785'],
            ['state'=>'19','name'=>'Timbío','code'=>'19,807'],
            ['state'=>'19','name'=>'Timbiquí','code'=>'19,809'],
            ['state'=>'19','name'=>'Toribio','code'=>'19,821'],
            ['state'=>'19','name'=>'Totoró','code'=>'19,824'],
            ['state'=>'19','name'=>'Villa Rica','code'=>'19,845'],
            ['state'=>'20','name'=>'Valledupar','code'=>'20,001'],
            ['state'=>'20','name'=>'Aguachica','code'=>'20,011'],
            ['state'=>'20','name'=>'Agustín Codazzi','code'=>'20,013'],
            ['state'=>'20','name'=>'Astrea','code'=>'20,032'],
            ['state'=>'20','name'=>'Becerril','code'=>'20,045'],
            ['state'=>'20','name'=>'Bosconia','code'=>'20,06'],
            ['state'=>'20','name'=>'Chimichagua','code'=>'20,175'],
            ['state'=>'20','name'=>'Chiriguaná','code'=>'20,178'],
            ['state'=>'20','name'=>'Curumaní','code'=>'20,228'],
            ['state'=>'20','name'=>'El Copey','code'=>'20,238'],
            ['state'=>'20','name'=>'El Paso','code'=>'20,25'],
            ['state'=>'20','name'=>'Gamarra','code'=>'20,295'],
            ['state'=>'20','name'=>'González','code'=>'20,31'],
            ['state'=>'20','name'=>'La Gloria','code'=>'20,383'],
            ['state'=>'76','name'=>'Jamundí','code'=>'76,364'],
            ['state'=>'20','name'=>'Manaure','code'=>'20,443'],
            ['state'=>'20','name'=>'Pailitas','code'=>'20,517'],
            ['state'=>'20','name'=>'Pelaya','code'=>'20,55'],
            ['state'=>'20','name'=>'Pueblo Bello','code'=>'20,57'],
            ['state'=>'27','name'=>'Tadó','code'=>'27,787'],
            ['state'=>'20','name'=>'La Paz','code'=>'20,621'],
            ['state'=>'20','name'=>'San Alberto','code'=>'20,71'],
            ['state'=>'20','name'=>'San Diego','code'=>'20,75'],
            ['state'=>'20','name'=>'San Martín','code'=>'20,77'],
            ['state'=>'20','name'=>'Tamalameque','code'=>'20,787'],
            ['state'=>'23','name'=>'Montería','code'=>'23,001'],
            ['state'=>'23','name'=>'Ayapel','code'=>'23,068'],
            ['state'=>'23','name'=>'Buenavista','code'=>'23,079'],
            ['state'=>'23','name'=>'Canalete','code'=>'23,09'],
            ['state'=>'23','name'=>'Cereté','code'=>'23,162'],
            ['state'=>'23','name'=>'Chimá','code'=>'23,168'],
            ['state'=>'23','name'=>'Chinú','code'=>'23,182'],
            ['state'=>'85','name'=>'Orocué','code'=>'85,23'],
            ['state'=>'23','name'=>'Cotorra','code'=>'23,3'],
            ['state'=>'73','name'=>'Líbano','code'=>'73,411'],
            ['state'=>'23','name'=>'Lorica','code'=>'23,417'],
            ['state'=>'23','name'=>'Los Córdobas','code'=>'23,419'],
            ['state'=>'23','name'=>'Momil','code'=>'23,464'],
            ['state'=>'23','name'=>'Moñitos','code'=>'23,5'],
            ['state'=>'23','name'=>'Planeta Rica','code'=>'23,555'],
            ['state'=>'23','name'=>'Pueblo Nuevo','code'=>'23,57'],
            ['state'=>'23','name'=>'Puerto Escondido','code'=>'23,574'],
            ['state'=>'25','name'=>'Yacopí','code'=>'25,885'],
            ['state'=>'23','name'=>'Purísima','code'=>'23,586'],
            ['state'=>'23','name'=>'Sahagún','code'=>'23,66'],
            ['state'=>'23','name'=>'San Andrés Sotavento','code'=>'23,67'],
            ['state'=>'23','name'=>'San Antero','code'=>'23,672'],
            ['state'=>'63','name'=>'Calarcá','code'=>'63,13'],
            ['state'=>'5','name'=>'Sonsón','code'=>'5,756'],
            ['state'=>'54','name'=>'El Carmen','code'=>'54,245'],
            ['state'=>'23','name'=>'San Pelayo','code'=>'23,686'],
            ['state'=>'23','name'=>'Tierralta','code'=>'23,807'],
            ['state'=>'23','name'=>'Tuchín','code'=>'23,815'],
            ['state'=>'23','name'=>'Valencia','code'=>'23,855'],
            ['state'=>'73','name'=>'Lérida','code'=>'73,408'],
            ['state'=>'25','name'=>'Anapoima','code'=>'25,035'],
            ['state'=>'25','name'=>'Arbeláez','code'=>'25,053'],
            ['state'=>'25','name'=>'Beltrán','code'=>'25,086'],
            ['state'=>'25','name'=>'Bituima','code'=>'25,095'],
            ['state'=>'25','name'=>'Bojacá','code'=>'25,099'],
            ['state'=>'25','name'=>'Cabrera','code'=>'25,12'],
            ['state'=>'25','name'=>'Cachipay','code'=>'25,123'],
            ['state'=>'25','name'=>'Cajicá','code'=>'25,126'],
            ['state'=>'25','name'=>'Caparrapí','code'=>'25,148'],
            ['state'=>'25','name'=>'Caqueza','code'=>'25,151'],
            ['state'=>'23','name'=>'La Apartada','code'=>'23,35'],
            ['state'=>'25','name'=>'Chaguaní','code'=>'25,168'],
            ['state'=>'25','name'=>'Chipaque','code'=>'25,178'],
            ['state'=>'25','name'=>'Choachí','code'=>'25,181'],
            ['state'=>'25','name'=>'Chocontá','code'=>'25,183'],
            ['state'=>'25','name'=>'Cogua','code'=>'25,2'],
            ['state'=>'25','name'=>'Cota','code'=>'25,214'],
            ['state'=>'25','name'=>'Cucunubá','code'=>'25,224'],
            ['state'=>'25','name'=>'El Colegio','code'=>'25,245'],
            ['state'=>'25','name'=>'El Rosal','code'=>'25,26'],
            ['state'=>'25','name'=>'Fomeque','code'=>'25,279'],
            ['state'=>'25','name'=>'Fosca','code'=>'25,281'],
            ['state'=>'25','name'=>'Funza','code'=>'25,286'],
            ['state'=>'25','name'=>'Fúquene','code'=>'25,288'],
            ['state'=>'25','name'=>'Gachala','code'=>'25,293'],
            ['state'=>'25','name'=>'Gachancipá','code'=>'25,295'],
            ['state'=>'25','name'=>'Gachetá','code'=>'25,297'],
            ['state'=>'13','name'=>'San Cristóbal','code'=>'13,62'],
            ['state'=>'25','name'=>'Girardot','code'=>'25,307'],
            ['state'=>'25','name'=>'Granada','code'=>'25,312'],
            ['state'=>'25','name'=>'Guachetá','code'=>'25,317'],
            ['state'=>'25','name'=>'Guaduas','code'=>'25,32'],
            ['state'=>'25','name'=>'Guasca','code'=>'25,322'],
            ['state'=>'25','name'=>'Guataquí','code'=>'25,324'],
            ['state'=>'25','name'=>'Guatavita','code'=>'25,326'],
            ['state'=>'25','name'=>'Fusagasugá','code'=>'25,29'],
            ['state'=>'25','name'=>'Guayabetal','code'=>'25,335'],
            ['state'=>'25','name'=>'Gutiérrez','code'=>'25,339'],
            ['state'=>'25','name'=>'Jerusalén','code'=>'25,368'],
            ['state'=>'25','name'=>'Junín','code'=>'25,372'],
            ['state'=>'25','name'=>'La Calera','code'=>'25,377'],
            ['state'=>'25','name'=>'La Mesa','code'=>'25,386'],
            ['state'=>'25','name'=>'La Palma','code'=>'25,394'],
            ['state'=>'25','name'=>'La Peña','code'=>'25,398'],
            ['state'=>'25','name'=>'La Vega','code'=>'25,402'],
            ['state'=>'25','name'=>'Lenguazaque','code'=>'25,407'],
            ['state'=>'25','name'=>'Macheta','code'=>'25,426'],
            ['state'=>'25','name'=>'Madrid','code'=>'25,43'],
            ['state'=>'25','name'=>'Manta','code'=>'25,436'],
            ['state'=>'25','name'=>'Medina','code'=>'25,438'],
            ['state'=>'25','name'=>'Mosquera','code'=>'25,473'],
            ['state'=>'25','name'=>'Nariño','code'=>'25,483'],
            ['state'=>'25','name'=>'Nemocón','code'=>'25,486'],
            ['state'=>'25','name'=>'Nilo','code'=>'25,488'],
            ['state'=>'25','name'=>'Nimaima','code'=>'25,489'],
            ['state'=>'25','name'=>'Nocaima','code'=>'25,491'],
            ['state'=>'25','name'=>'Venecia','code'=>'25,506'],
            ['state'=>'25','name'=>'Pacho','code'=>'25,513'],
            ['state'=>'25','name'=>'Paime','code'=>'25,518'],
            ['state'=>'25','name'=>'Pandi','code'=>'25,524'],
            ['state'=>'25','name'=>'Paratebueno','code'=>'25,53'],
            ['state'=>'25','name'=>'Pasca','code'=>'25,535'],
            ['state'=>'25','name'=>'Puerto Salgar','code'=>'25,572'],
            ['state'=>'25','name'=>'Pulí','code'=>'25,58'],
            ['state'=>'25','name'=>'Quebradanegra','code'=>'25,592'],
            ['state'=>'25','name'=>'Quetame','code'=>'25,594'],
            ['state'=>'25','name'=>'Quipile','code'=>'25,596'],
            ['state'=>'25','name'=>'Apulo','code'=>'25,599'],
            ['state'=>'25','name'=>'Ricaurte','code'=>'25,612'],
            ['state'=>'13','name'=>'Zambrano','code'=>'13,894'],
            ['state'=>'25','name'=>'San Bernardo','code'=>'25,649'],
            ['state'=>'25','name'=>'San Cayetano','code'=>'25,653'],
            ['state'=>'25','name'=>'San Francisco','code'=>'25,658'],
            ['state'=>'15','name'=>'La Uvita','code'=>'15,403'],
            ['state'=>'25','name'=>'Zipaquirá','code'=>'25,899'],
            ['state'=>'25','name'=>'Sesquilé','code'=>'25,736'],
            ['state'=>'25','name'=>'Sibaté','code'=>'25,74'],
            ['state'=>'25','name'=>'Silvania','code'=>'25,743'],
            ['state'=>'25','name'=>'Simijaca','code'=>'25,745'],
            ['state'=>'25','name'=>'Soacha','code'=>'25,754'],
            ['state'=>'25','name'=>'Subachoque','code'=>'25,769'],
            ['state'=>'25','name'=>'Suesca','code'=>'25,772'],
            ['state'=>'25','name'=>'Supatá','code'=>'25,777'],
            ['state'=>'25','name'=>'Susa','code'=>'25,779'],
            ['state'=>'25','name'=>'Sutatausa','code'=>'25,781'],
            ['state'=>'25','name'=>'Tabio','code'=>'25,785'],
            ['state'=>'63','name'=>'Génova','code'=>'63,302'],
            ['state'=>'25','name'=>'Tausa','code'=>'25,793'],
            ['state'=>'25','name'=>'Tena','code'=>'25,797'],
            ['state'=>'25','name'=>'Tenjo','code'=>'25,799'],
            ['state'=>'25','name'=>'Tibacuy','code'=>'25,805'],
            ['state'=>'25','name'=>'Tibirita','code'=>'25,807'],
            ['state'=>'25','name'=>'Tocaima','code'=>'25,815'],
            ['state'=>'25','name'=>'Tocancipá','code'=>'25,817'],
            ['state'=>'25','name'=>'Topaipí','code'=>'25,823'],
            ['state'=>'25','name'=>'Ubalá','code'=>'25,839'],
            ['state'=>'25','name'=>'Ubaque','code'=>'25,841'],
            ['state'=>'73','name'=>'Suárez','code'=>'73,77'],
            ['state'=>'25','name'=>'Une','code'=>'25,845'],
            ['state'=>'25','name'=>'Útica','code'=>'25,851'],
            ['state'=>'50','name'=>'Castilla la Nueva','code'=>'50,15'],
            ['state'=>'25','name'=>'Vianí','code'=>'25,867'],
            ['state'=>'25','name'=>'Villagómez','code'=>'25,871'],
            ['state'=>'25','name'=>'Villapinzón','code'=>'25,873'],
            ['state'=>'25','name'=>'Villeta','code'=>'25,875'],
            ['state'=>'25','name'=>'Viotá','code'=>'25,878'],
            ['state'=>'25','name'=>'Zipacón','code'=>'25,898'],
            ['state'=>'27','name'=>'Quibdó','code'=>'27,001'],
            ['state'=>'27','name'=>'Acandí','code'=>'27,006'],
            ['state'=>'27','name'=>'Alto Baudo','code'=>'27,025'],
            ['state'=>'27','name'=>'Atrato','code'=>'27,05'],
            ['state'=>'27','name'=>'Bagadó','code'=>'27,073'],
            ['state'=>'27','name'=>'Bahía Solano','code'=>'27,075'],
            ['state'=>'27','name'=>'Bajo Baudó','code'=>'27,077'],
            ['state'=>'15','name'=>'Belén','code'=>'15,087'],
            ['state'=>'27','name'=>'Bojaya','code'=>'27,099'],
            ['state'=>'27','name'=>'Unión Panamericana','code'=>'27,81'],
            ['state'=>'47','name'=>'Pueblo Viejo','code'=>'47,57'],
            ['state'=>'27','name'=>'Cértegui','code'=>'27,16'],
            ['state'=>'27','name'=>'Condoto','code'=>'27,205'],
            ['state'=>'86','name'=>'Villagarzón','code'=>'86,885'],
            ['state'=>'25','name'=>'Facatativá','code'=>'25,269'],
            ['state'=>'27','name'=>'Juradó','code'=>'27,372'],
            ['state'=>'27','name'=>'Lloró','code'=>'27,413'],
            ['state'=>'27','name'=>'Medio Atrato','code'=>'27,425'],
            ['state'=>'27','name'=>'Medio Baudó','code'=>'27,43'],
            ['state'=>'27','name'=>'Medio San Juan','code'=>'27,45'],
            ['state'=>'27','name'=>'Nóvita','code'=>'27,491'],
            ['state'=>'27','name'=>'Nuquí','code'=>'27,495'],
            ['state'=>'27','name'=>'Río Iro','code'=>'27,58'],
            ['state'=>'27','name'=>'Río Quito','code'=>'27,6'],
            ['state'=>'27','name'=>'Riosucio','code'=>'27,615'],
            ['state'=>'23','name'=>'Puerto Libertador','code'=>'23,58'],
            ['state'=>'27','name'=>'Sipí','code'=>'27,745'],
            ['state'=>'27','name'=>'Unguía','code'=>'27,8'],
            ['state'=>'41','name'=>'Neiva','code'=>'41,001'],
            ['state'=>'41','name'=>'Acevedo','code'=>'41,006'],
            ['state'=>'41','name'=>'Agrado','code'=>'41,013'],
            ['state'=>'41','name'=>'Aipe','code'=>'41,016'],
            ['state'=>'41','name'=>'Algeciras','code'=>'41,02'],
            ['state'=>'41','name'=>'Altamira','code'=>'41,026'],
            ['state'=>'41','name'=>'Baraya','code'=>'41,078'],
            ['state'=>'41','name'=>'Campoalegre','code'=>'41,132'],
            ['state'=>'41','name'=>'Colombia','code'=>'41,206'],
            ['state'=>'41','name'=>'Elías','code'=>'41,244'],
            ['state'=>'41','name'=>'Garzón','code'=>'41,298'],
            ['state'=>'41','name'=>'Gigante','code'=>'41,306'],
            ['state'=>'41','name'=>'Guadalupe','code'=>'41,319'],
            ['state'=>'41','name'=>'Hobo','code'=>'41,349'],
            ['state'=>'41','name'=>'Iquira','code'=>'41,357'],
            ['state'=>'41','name'=>'Isnos','code'=>'41,359'],
            ['state'=>'41','name'=>'La Argentina','code'=>'41,378'],
            ['state'=>'41','name'=>'La Plata','code'=>'41,396'],
            ['state'=>'17','name'=>'Marquetalia','code'=>'17,444'],
            ['state'=>'41','name'=>'Nátaga','code'=>'41,483'],
            ['state'=>'41','name'=>'Oporapa','code'=>'41,503'],
            ['state'=>'41','name'=>'Paicol','code'=>'41,518'],
            ['state'=>'41','name'=>'Palermo','code'=>'41,524'],
            ['state'=>'41','name'=>'Palestina','code'=>'41,53'],
            ['state'=>'41','name'=>'Pital','code'=>'41,548'],
            ['state'=>'41','name'=>'Pitalito','code'=>'41,551'],
            ['state'=>'41','name'=>'Rivera','code'=>'41,615'],
            ['state'=>'41','name'=>'Saladoblanco','code'=>'41,66'],
            ['state'=>'52','name'=>'Arboleda','code'=>'52,051'],
            ['state'=>'41','name'=>'Santa María','code'=>'41,676'],
            ['state'=>'41','name'=>'Suaza','code'=>'41,77'],
            ['state'=>'41','name'=>'Tarqui','code'=>'41,791'],
            ['state'=>'41','name'=>'Tesalia','code'=>'41,797'],
            ['state'=>'41','name'=>'Tello','code'=>'41,799'],
            ['state'=>'41','name'=>'Teruel','code'=>'41,801'],
            ['state'=>'41','name'=>'Timaná','code'=>'41,807'],
            ['state'=>'41','name'=>'Villavieja','code'=>'41,872'],
            ['state'=>'41','name'=>'Yaguará','code'=>'41,885'],
            ['state'=>'44','name'=>'Riohacha','code'=>'44,001'],
            ['state'=>'44','name'=>'Albania','code'=>'44,035'],
            ['state'=>'44','name'=>'Barrancas','code'=>'44,078'],
            ['state'=>'44','name'=>'Dibula','code'=>'44,09'],
            ['state'=>'44','name'=>'Distracción','code'=>'44,098'],
            ['state'=>'44','name'=>'El Molino','code'=>'44,11'],
            ['state'=>'44','name'=>'Fonseca','code'=>'44,279'],
            ['state'=>'44','name'=>'Hatonuevo','code'=>'44,378'],
            ['state'=>'44','name'=>'Maicao','code'=>'44,43'],
            ['state'=>'44','name'=>'Manaure','code'=>'44,56'],
            ['state'=>'44','name'=>'Uribia','code'=>'44,847'],
            ['state'=>'44','name'=>'Urumita','code'=>'44,855'],
            ['state'=>'44','name'=>'Villanueva','code'=>'44,874'],
            ['state'=>'47','name'=>'Santa Marta','code'=>'47,001'],
            ['state'=>'47','name'=>'Algarrobo','code'=>'47,03'],
            ['state'=>'47','name'=>'Aracataca','code'=>'47,053'],
            ['state'=>'47','name'=>'Ariguaní','code'=>'47,058'],
            ['state'=>'47','name'=>'Cerro San Antonio','code'=>'47,161'],
            ['state'=>'47','name'=>'Chivolo','code'=>'47,17'],
            ['state'=>'47','name'=>'Concordia','code'=>'47,205'],
            ['state'=>'47','name'=>'El Banco','code'=>'47,245'],
            ['state'=>'47','name'=>'El Piñon','code'=>'47,258'],
            ['state'=>'47','name'=>'El Retén','code'=>'47,268'],
            ['state'=>'47','name'=>'Fundación','code'=>'47,288'],
            ['state'=>'47','name'=>'Guamal','code'=>'47,318'],
            ['state'=>'47','name'=>'Nueva Granada','code'=>'47,46'],
            ['state'=>'47','name'=>'Pedraza','code'=>'47,541'],
            ['state'=>'47','name'=>'Pivijay','code'=>'47,551'],
            ['state'=>'47','name'=>'Plato','code'=>'47,555'],
            ['state'=>'47','name'=>'Remolino','code'=>'47,605'],
            ['state'=>'47','name'=>'Salamina','code'=>'47,675'],
            ['state'=>'47','name'=>'San Zenón','code'=>'47,703'],
            ['state'=>'47','name'=>'Santa Ana','code'=>'47,707'],
            ['state'=>'47','name'=>'Sitionuevo','code'=>'47,745'],
            ['state'=>'47','name'=>'Tenerife','code'=>'47,798'],
            ['state'=>'47','name'=>'Zapayán','code'=>'47,96'],
            ['state'=>'47','name'=>'Zona Bananera','code'=>'47,98'],
            ['state'=>'50','name'=>'Villavicencio','code'=>'50,001'],
            ['state'=>'50','name'=>'Acacias','code'=>'50,006'],
            ['state'=>'50','name'=>'Cabuyaro','code'=>'50,124'],
            ['state'=>'50','name'=>'Cubarral','code'=>'50,223'],
            ['state'=>'50','name'=>'Cumaral','code'=>'50,226'],
            ['state'=>'50','name'=>'El Calvario','code'=>'50,245'],
            ['state'=>'50','name'=>'El Castillo','code'=>'50,251'],
            ['state'=>'50','name'=>'El Dorado','code'=>'50,27'],
            ['state'=>'76','name'=>'Buenaventura','code'=>'76,109'],
            ['state'=>'50','name'=>'Granada','code'=>'50,313'],
            ['state'=>'50','name'=>'Guamal','code'=>'50,318'],
            ['state'=>'50','name'=>'Mapiripán','code'=>'50,325'],
            ['state'=>'50','name'=>'Mesetas','code'=>'50,33'],
            ['state'=>'50','name'=>'La Macarena','code'=>'50,35'],
            ['state'=>'50','name'=>'Uribe','code'=>'50,37'],
            ['state'=>'50','name'=>'Lejanías','code'=>'50,4'],
            ['state'=>'50','name'=>'Puerto Concordia','code'=>'50,45'],
            ['state'=>'50','name'=>'Puerto Gaitán','code'=>'50,568'],
            ['state'=>'50','name'=>'Puerto López','code'=>'50,573'],
            ['state'=>'50','name'=>'Puerto Lleras','code'=>'50,577'],
            ['state'=>'50','name'=>'Puerto Rico','code'=>'50,59'],
            ['state'=>'50','name'=>'Restrepo','code'=>'50,606'],
            ['state'=>'47','name'=>'Ciénaga','code'=>'47,189'],
            ['state'=>'8','name'=>'Ponedera','code'=>'8,56'],
            ['state'=>'50','name'=>'San Juanito','code'=>'50,686'],
            ['state'=>'50','name'=>'San Martín','code'=>'50,689'],
            ['state'=>'50','name'=>'Vista Hermosa','code'=>'50,711'],
            ['state'=>'52','name'=>'Pasto','code'=>'52,001'],
            ['state'=>'52','name'=>'Albán','code'=>'52,019'],
            ['state'=>'52','name'=>'Aldana','code'=>'52,022'],
            ['state'=>'52','name'=>'Ancuyá','code'=>'52,036'],
            ['state'=>'15','name'=>'Tununguá','code'=>'15,832'],
            ['state'=>'52','name'=>'Barbacoas','code'=>'52,079'],
            ['state'=>'15','name'=>'Motavita','code'=>'15,476'],
            ['state'=>'23','name'=>'San Bernardo del Viento','code'=>'23,675'],
            ['state'=>'52','name'=>'Colón','code'=>'52,203'],
            ['state'=>'52','name'=>'Consaca','code'=>'52,207'],
            ['state'=>'52','name'=>'Contadero','code'=>'52,21'],
            ['state'=>'52','name'=>'Córdoba','code'=>'52,215'],
            ['state'=>'52','name'=>'Cuaspud','code'=>'52,224'],
            ['state'=>'52','name'=>'Cumbal','code'=>'52,227'],
            ['state'=>'52','name'=>'Cumbitara','code'=>'52,233'],
            ['state'=>'52','name'=>'El Charco','code'=>'52,25'],
            ['state'=>'52','name'=>'El Peñol','code'=>'52,254'],
            ['state'=>'52','name'=>'El Rosario','code'=>'52,256'],
            ['state'=>'27','name'=>'Istmina','code'=>'27,361'],
            ['state'=>'52','name'=>'El Tambo','code'=>'52,26'],
            ['state'=>'52','name'=>'Funes','code'=>'52,287'],
            ['state'=>'52','name'=>'Guachucal','code'=>'52,317'],
            ['state'=>'52','name'=>'Guaitarilla','code'=>'52,32'],
            ['state'=>'52','name'=>'Gualmatán','code'=>'52,323'],
            ['state'=>'52','name'=>'Iles','code'=>'52,352'],
            ['state'=>'52','name'=>'Imués','code'=>'52,354'],
            ['state'=>'52','name'=>'Ipiales','code'=>'52,356'],
            ['state'=>'52','name'=>'La Cruz','code'=>'52,378'],
            ['state'=>'52','name'=>'La Florida','code'=>'52,381'],
            ['state'=>'52','name'=>'La Llanada','code'=>'52,385'],
            ['state'=>'52','name'=>'La Tola','code'=>'52,39'],
            ['state'=>'52','name'=>'La Unión','code'=>'52,399'],
            ['state'=>'52','name'=>'Leiva','code'=>'52,405'],
            ['state'=>'52','name'=>'Linares','code'=>'52,411'],
            ['state'=>'52','name'=>'Los Andes','code'=>'52,418'],
            ['state'=>'52','name'=>'Magüí','code'=>'52,427'],
            ['state'=>'52','name'=>'Mallama','code'=>'52,435'],
            ['state'=>'52','name'=>'Mosquera','code'=>'52,473'],
            ['state'=>'52','name'=>'Nariño','code'=>'52,48'],
            ['state'=>'52','name'=>'Olaya Herrera','code'=>'52,49'],
            ['state'=>'52','name'=>'Ospina','code'=>'52,506'],
            ['state'=>'52','name'=>'Francisco Pizarro','code'=>'52,52'],
            ['state'=>'52','name'=>'Policarpa','code'=>'52,54'],
            ['state'=>'52','name'=>'Potosí','code'=>'52,56'],
            ['state'=>'52','name'=>'Providencia','code'=>'52,565'],
            ['state'=>'52','name'=>'Puerres','code'=>'52,573'],
            ['state'=>'52','name'=>'Pupiales','code'=>'52,585'],
            ['state'=>'52','name'=>'Ricaurte','code'=>'52,612'],
            ['state'=>'52','name'=>'Roberto Payán','code'=>'52,621'],
            ['state'=>'52','name'=>'Samaniego','code'=>'52,678'],
            ['state'=>'52','name'=>'Sandoná','code'=>'52,683'],
            ['state'=>'52','name'=>'San Bernardo','code'=>'52,685'],
            ['state'=>'52','name'=>'San Lorenzo','code'=>'52,687'],
            ['state'=>'52','name'=>'San Pablo','code'=>'52,693'],
            ['state'=>'5','name'=>'Belmira','code'=>'5,086'],
            ['state'=>'15','name'=>'Ciénega','code'=>'15,189'],
            ['state'=>'52','name'=>'Santa Bárbara','code'=>'52,696'],
            ['state'=>'52','name'=>'Sapuyes','code'=>'52,72'],
            ['state'=>'52','name'=>'Taminango','code'=>'52,786'],
            ['state'=>'52','name'=>'Tangua','code'=>'52,788'],
            ['state'=>'52','name'=>'Santacruz','code'=>'52,699'],
            ['state'=>'52','name'=>'Túquerres','code'=>'52,838'],
            ['state'=>'52','name'=>'Yacuanquer','code'=>'52,885'],
            ['state'=>'68','name'=>'Puerto Wilches','code'=>'68,575'],
            ['state'=>'68','name'=>'Puerto Parra','code'=>'68,573'],
            ['state'=>'63','name'=>'Armenia','code'=>'63,001'],
            ['state'=>'63','name'=>'Buenavista','code'=>'63,111'],
            ['state'=>'63','name'=>'Circasia','code'=>'63,19'],
            ['state'=>'63','name'=>'Córdoba','code'=>'63,212'],
            ['state'=>'63','name'=>'Filandia','code'=>'63,272'],
            ['state'=>'63','name'=>'La Tebaida','code'=>'63,401'],
            ['state'=>'63','name'=>'Montenegro','code'=>'63,47'],
            ['state'=>'63','name'=>'Pijao','code'=>'63,548'],
            ['state'=>'63','name'=>'Quimbaya','code'=>'63,594'],
            ['state'=>'63','name'=>'Salento','code'=>'63,69'],
            ['state'=>'66','name'=>'Pereira','code'=>'66,001'],
            ['state'=>'66','name'=>'Apía','code'=>'66,045'],
            ['state'=>'66','name'=>'Balboa','code'=>'66,075'],
            ['state'=>'66','name'=>'Dosquebradas','code'=>'66,17'],
            ['state'=>'66','name'=>'Guática','code'=>'66,318'],
            ['state'=>'66','name'=>'La Celia','code'=>'66,383'],
            ['state'=>'66','name'=>'La Virginia','code'=>'66,4'],
            ['state'=>'66','name'=>'Marsella','code'=>'66,44'],
            ['state'=>'66','name'=>'Mistrató','code'=>'66,456'],
            ['state'=>'66','name'=>'Pueblo Rico','code'=>'66,572'],
            ['state'=>'66','name'=>'Quinchía','code'=>'66,594'],
            ['state'=>'66','name'=>'Santuario','code'=>'66,687'],
            ['state'=>'68','name'=>'Bucaramanga','code'=>'68,001'],
            ['state'=>'68','name'=>'Aguada','code'=>'68,013'],
            ['state'=>'68','name'=>'Albania','code'=>'68,02'],
            ['state'=>'68','name'=>'Aratoca','code'=>'68,051'],
            ['state'=>'68','name'=>'Barbosa','code'=>'68,077'],
            ['state'=>'68','name'=>'Barichara','code'=>'68,079'],
            ['state'=>'68','name'=>'Barrancabermeja','code'=>'68,081'],
            ['state'=>'68','name'=>'Betulia','code'=>'68,092'],
            ['state'=>'68','name'=>'Bolívar','code'=>'68,101'],
            ['state'=>'68','name'=>'Cabrera','code'=>'68,121'],
            ['state'=>'68','name'=>'California','code'=>'68,132'],
            ['state'=>'68','name'=>'Carcasí','code'=>'68,152'],
            ['state'=>'68','name'=>'Cepitá','code'=>'68,16'],
            ['state'=>'68','name'=>'Cerrito','code'=>'68,162'],
            ['state'=>'68','name'=>'Charalá','code'=>'68,167'],
            ['state'=>'68','name'=>'Charta','code'=>'68,169'],
            ['state'=>'68','name'=>'Chipatá','code'=>'68,179'],
            ['state'=>'68','name'=>'Cimitarra','code'=>'68,19'],
            ['state'=>'68','name'=>'Concepción','code'=>'68,207'],
            ['state'=>'68','name'=>'Confines','code'=>'68,209'],
            ['state'=>'68','name'=>'Contratación','code'=>'68,211'],
            ['state'=>'68','name'=>'Coromoro','code'=>'68,217'],
            ['state'=>'68','name'=>'Curití','code'=>'68,229'],
            ['state'=>'68','name'=>'El Guacamayo','code'=>'68,245'],
            ['state'=>'68','name'=>'El Playón','code'=>'68,255'],
            ['state'=>'68','name'=>'Encino','code'=>'68,264'],
            ['state'=>'68','name'=>'Enciso','code'=>'68,266'],
            ['state'=>'68','name'=>'Florián','code'=>'68,271'],
            ['state'=>'68','name'=>'Floridablanca','code'=>'68,276'],
            ['state'=>'68','name'=>'Galán','code'=>'68,296'],
            ['state'=>'68','name'=>'Gambita','code'=>'68,298'],
            ['state'=>'68','name'=>'Girón','code'=>'68,307'],
            ['state'=>'68','name'=>'Guaca','code'=>'68,318'],
            ['state'=>'68','name'=>'Guadalupe','code'=>'68,32'],
            ['state'=>'68','name'=>'Guapotá','code'=>'68,322'],
            ['state'=>'68','name'=>'Guavatá','code'=>'68,324'],
            ['state'=>'68','name'=>'Güepsa','code'=>'68,327'],
            ['state'=>'68','name'=>'Jesús María','code'=>'68,368'],
            ['state'=>'68','name'=>'Jordán','code'=>'68,37'],
            ['state'=>'68','name'=>'La Belleza','code'=>'68,377'],
            ['state'=>'68','name'=>'Landázuri','code'=>'68,385'],
            ['state'=>'68','name'=>'La Paz','code'=>'68,397'],
            ['state'=>'68','name'=>'Lebríja','code'=>'68,406'],
            ['state'=>'68','name'=>'Los Santos','code'=>'68,418'],
            ['state'=>'68','name'=>'Macaravita','code'=>'68,425'],
            ['state'=>'68','name'=>'Málaga','code'=>'68,432'],
            ['state'=>'68','name'=>'Matanza','code'=>'68,444'],
            ['state'=>'68','name'=>'Mogotes','code'=>'68,464'],
            ['state'=>'68','name'=>'Molagavita','code'=>'68,468'],
            ['state'=>'68','name'=>'Ocamonte','code'=>'68,498'],
            ['state'=>'68','name'=>'Oiba','code'=>'68,5'],
            ['state'=>'68','name'=>'Onzaga','code'=>'68,502'],
            ['state'=>'68','name'=>'Palmar','code'=>'68,522'],
            ['state'=>'68','name'=>'Páramo','code'=>'68,533'],
            ['state'=>'68','name'=>'Piedecuesta','code'=>'68,547'],
            ['state'=>'68','name'=>'Pinchote','code'=>'68,549'],
            ['state'=>'68','name'=>'Puente Nacional','code'=>'68,572'],
            ['state'=>'68','name'=>'Rionegro','code'=>'68,615'],
            ['state'=>'68','name'=>'San Andrés','code'=>'68,669'],
            ['state'=>'68','name'=>'San Gil','code'=>'68,679'],
            ['state'=>'68','name'=>'San Joaquín','code'=>'68,682'],
            ['state'=>'68','name'=>'San Miguel','code'=>'68,686'],
            ['state'=>'68','name'=>'Santa Bárbara','code'=>'68,705'],
            ['state'=>'68','name'=>'Simacota','code'=>'68,745'],
            ['state'=>'68','name'=>'Socorro','code'=>'68,755'],
            ['state'=>'68','name'=>'Suaita','code'=>'68,77'],
            ['state'=>'68','name'=>'Sucre','code'=>'68,773'],
            ['state'=>'68','name'=>'Suratá','code'=>'68,78'],
            ['state'=>'68','name'=>'Tona','code'=>'68,82'],
            ['state'=>'68','name'=>'Vélez','code'=>'68,861'],
            ['state'=>'68','name'=>'Vetas','code'=>'68,867'],
            ['state'=>'68','name'=>'Villanueva','code'=>'68,872'],
            ['state'=>'68','name'=>'Zapatoca','code'=>'68,895'],
            ['state'=>'70','name'=>'Sincelejo','code'=>'70,001'],
            ['state'=>'70','name'=>'Buenavista','code'=>'70,11'],
            ['state'=>'70','name'=>'Caimito','code'=>'70,124'],
            ['state'=>'70','name'=>'Coloso','code'=>'70,204'],
            ['state'=>'70','name'=>'Coveñas','code'=>'70,221'],
            ['state'=>'70','name'=>'Chalán','code'=>'70,23'],
            ['state'=>'70','name'=>'El Roble','code'=>'70,233'],
            ['state'=>'70','name'=>'Galeras','code'=>'70,235'],
            ['state'=>'70','name'=>'Guaranda','code'=>'70,265'],
            ['state'=>'70','name'=>'La Unión','code'=>'70,4'],
            ['state'=>'70','name'=>'Los Palmitos','code'=>'70,418'],
            ['state'=>'70','name'=>'Majagual','code'=>'70,429'],
            ['state'=>'70','name'=>'Morroa','code'=>'70,473'],
            ['state'=>'70','name'=>'Ovejas','code'=>'70,508'],
            ['state'=>'70','name'=>'Palmito','code'=>'70,523'],
            ['state'=>'70','name'=>'San Benito Abad','code'=>'70,678'],
            ['state'=>'70','name'=>'San Marcos','code'=>'70,708'],
            ['state'=>'70','name'=>'San Onofre','code'=>'70,713'],
            ['state'=>'70','name'=>'San Pedro','code'=>'70,717'],
            ['state'=>'70','name'=>'Sucre','code'=>'70,771'],
            ['state'=>'70','name'=>'Tolú Viejo','code'=>'70,823'],
            ['state'=>'73','name'=>'Alpujarra','code'=>'73,024'],
            ['state'=>'73','name'=>'Alvarado','code'=>'73,026'],
            ['state'=>'73','name'=>'Ambalema','code'=>'73,03'],
            ['state'=>'73','name'=>'Armero','code'=>'73,055'],
            ['state'=>'73','name'=>'Ataco','code'=>'73,067'],
            ['state'=>'73','name'=>'Cajamarca','code'=>'73,124'],
            ['state'=>'73','name'=>'Chaparral','code'=>'73,168'],
            ['state'=>'73','name'=>'Coello','code'=>'73,2'],
            ['state'=>'73','name'=>'Coyaima','code'=>'73,217'],
            ['state'=>'73','name'=>'Cunday','code'=>'73,226'],
            ['state'=>'73','name'=>'Dolores','code'=>'73,236'],
            ['state'=>'73','name'=>'Espinal','code'=>'73,268'],
            ['state'=>'73','name'=>'Falan','code'=>'73,27'],
            ['state'=>'73','name'=>'Flandes','code'=>'73,275'],
            ['state'=>'73','name'=>'Fresno','code'=>'73,283'],
            ['state'=>'73','name'=>'Guamo','code'=>'73,319'],
            ['state'=>'73','name'=>'Herveo','code'=>'73,347'],
            ['state'=>'73','name'=>'Honda','code'=>'73,349'],
            ['state'=>'73','name'=>'Icononzo','code'=>'73,352'],
            ['state'=>'73','name'=>'Mariquita','code'=>'73,443'],
            ['state'=>'73','name'=>'Melgar','code'=>'73,449'],
            ['state'=>'73','name'=>'Murillo','code'=>'73,461'],
            ['state'=>'73','name'=>'Natagaima','code'=>'73,483'],
            ['state'=>'73','name'=>'Ortega','code'=>'73,504'],
            ['state'=>'73','name'=>'Palocabildo','code'=>'73,52'],
            ['state'=>'73','name'=>'Piedras','code'=>'73,547'],
            ['state'=>'73','name'=>'Planadas','code'=>'73,555'],
            ['state'=>'73','name'=>'Prado','code'=>'73,563'],
            ['state'=>'73','name'=>'Purificación','code'=>'73,585'],
            ['state'=>'73','name'=>'Rio Blanco','code'=>'73,616'],
            ['state'=>'73','name'=>'Roncesvalles','code'=>'73,622'],
            ['state'=>'73','name'=>'Rovira','code'=>'73,624'],
            ['state'=>'73','name'=>'Saldaña','code'=>'73,671'],
            ['state'=>'73','name'=>'Santa Isabel','code'=>'73,686'],
            ['state'=>'73','name'=>'Venadillo','code'=>'73,861'],
            ['state'=>'73','name'=>'Villahermosa','code'=>'73,87'],
            ['state'=>'73','name'=>'Villarrica','code'=>'73,873'],
            ['state'=>'81','name'=>'Arauquita','code'=>'81,065'],
            ['state'=>'81','name'=>'Cravo Norte','code'=>'81,22'],
            ['state'=>'81','name'=>'Fortul','code'=>'81,3'],
            ['state'=>'81','name'=>'Puerto Rondón','code'=>'81,591'],
            ['state'=>'81','name'=>'Saravena','code'=>'81,736'],
            ['state'=>'81','name'=>'Tame','code'=>'81,794'],
            ['state'=>'81','name'=>'Arauca','code'=>'81,001'],
            ['state'=>'85','name'=>'Yopal','code'=>'85,001'],
            ['state'=>'85','name'=>'Aguazul','code'=>'85,01'],
            ['state'=>'85','name'=>'Chámeza','code'=>'85,015'],
            ['state'=>'85','name'=>'Hato Corozal','code'=>'85,125'],
            ['state'=>'85','name'=>'La Salina','code'=>'85,136'],
            ['state'=>'85','name'=>'Monterrey','code'=>'85,162'],
            ['state'=>'85','name'=>'Pore','code'=>'85,263'],
            ['state'=>'85','name'=>'Recetor','code'=>'85,279'],
            ['state'=>'85','name'=>'Sabanalarga','code'=>'85,3'],
            ['state'=>'85','name'=>'Sácama','code'=>'85,315'],
            ['state'=>'85','name'=>'Tauramena','code'=>'85,41'],
            ['state'=>'85','name'=>'Trinidad','code'=>'85,43'],
            ['state'=>'85','name'=>'Villanueva','code'=>'85,44'],
            ['state'=>'86','name'=>'Mocoa','code'=>'86,001'],
            ['state'=>'86','name'=>'Colón','code'=>'86,219'],
            ['state'=>'86','name'=>'Orito','code'=>'86,32'],
            ['state'=>'86','name'=>'Puerto Caicedo','code'=>'86,569'],
            ['state'=>'86','name'=>'Puerto Guzmán','code'=>'86,571'],
            ['state'=>'86','name'=>'Leguízamo','code'=>'86,573'],
            ['state'=>'86','name'=>'Sibundoy','code'=>'86,749'],
            ['state'=>'86','name'=>'San Francisco','code'=>'86,755'],
            ['state'=>'86','name'=>'San Miguel','code'=>'86,757'],
            ['state'=>'86','name'=>'Santiago','code'=>'86,76'],
            ['state'=>'91','name'=>'Leticia','code'=>'91,001'],
            ['state'=>'91','name'=>'El Encanto','code'=>'91,263'],
            ['state'=>'91','name'=>'La Chorrera','code'=>'91,405'],
            ['state'=>'91','name'=>'La Pedrera','code'=>'91,407'],
            ['state'=>'91','name'=>'La Victoria','code'=>'91,43'],
            ['state'=>'91','name'=>'Puerto Arica','code'=>'91,536'],
            ['state'=>'91','name'=>'Puerto Nariño','code'=>'91,54'],
            ['state'=>'91','name'=>'Puerto Santander','code'=>'91,669'],
            ['state'=>'91','name'=>'Tarapacá','code'=>'91,798'],
            ['state'=>'94','name'=>'Inírida','code'=>'94,001'],
            ['state'=>'94','name'=>'Barranco Minas','code'=>'94,343'],
            ['state'=>'94','name'=>'Mapiripana','code'=>'94,663'],
            ['state'=>'94','name'=>'San Felipe','code'=>'94,883'],
            ['state'=>'94','name'=>'Puerto Colombia','code'=>'94,884'],
            ['state'=>'94','name'=>'La Guadalupe','code'=>'94,885'],
            ['state'=>'94','name'=>'Cacahual','code'=>'94,886'],
            ['state'=>'94','name'=>'Pana Pana','code'=>'94,887'],
            ['state'=>'94','name'=>'Morichal','code'=>'94,888'],
            ['state'=>'97','name'=>'Mitú','code'=>'97,001'],
            ['state'=>'97','name'=>'Caruru','code'=>'97,161'],
            ['state'=>'97','name'=>'Pacoa','code'=>'97,511'],
            ['state'=>'97','name'=>'Taraira','code'=>'97,666'],
            ['state'=>'97','name'=>'Papunaua','code'=>'97,777'],
            ['state'=>'99','name'=>'Puerto Carreño','code'=>'99,001'],
            ['state'=>'99','name'=>'La Primavera','code'=>'99,524'],
            ['state'=>'99','name'=>'Santa Rosalía','code'=>'99,624'],
            ['state'=>'99','name'=>'Cumaribo','code'=>'99,773'],
            ['state'=>'18','name'=>'San José del Fragua','code'=>'18,61'],
            ['state'=>'50','name'=>'Barranca de Upía','code'=>'50,11'],
            ['state'=>'68','name'=>'Palmas del Socorro','code'=>'68,524'],
            ['state'=>'25','name'=>'San Juan de Río Seco','code'=>'25,662'],
            ['state'=>'8','name'=>'Juan de Acosta','code'=>'8,372'],
            ['state'=>'50','name'=>'Fuente de Oro','code'=>'50,287'],
            ['state'=>'85','name'=>'San Luis de Gaceno','code'=>'85,325'],
            ['state'=>'27','name'=>'El Litoral del San Juan','code'=>'27,25'],
            ['state'=>'25','name'=>'Villa de San Diego de Ubate','code'=>'25,843'],
            ['state'=>'13','name'=>'Barranco de Loba','code'=>'13,074'],
            ['state'=>'15','name'=>'Togüí','code'=>'15,816'],
            ['state'=>'13','name'=>'Santa Rosa del Sur','code'=>'13,688'],
            ['state'=>'27','name'=>'El Cantón del San Pablo','code'=>'27,135'],
            ['state'=>'15','name'=>'Villa de Leyva','code'=>'15,407'],
            ['state'=>'47','name'=>'San Sebastián de Buenavista','code'=>'47,692'],
            ['state'=>'15','name'=>'Paz de Río','code'=>'15,537'],
            ['state'=>'13','name'=>'Hatillo de Loba','code'=>'13,3'],
            ['state'=>'47','name'=>'Sabanas de San Angel','code'=>'47,66'],
            ['state'=>'95','name'=>'Calamar','code'=>'95,015'],
            ['state'=>'20','name'=>'Río de Oro','code'=>'20,614'],
            ['state'=>'5','name'=>'San Pedro de Uraba','code'=>'5,665'],
            ['state'=>'95','name'=>'San José del Guaviare','code'=>'95,001'],
            ['state'=>'15','name'=>'Santa Rosa de Viterbo','code'=>'15,693'],
            ['state'=>'19','name'=>'Santander de Quilichao','code'=>'19,698'],
            ['state'=>'95','name'=>'Miraflores','code'=>'95,2'],
            ['state'=>'5','name'=>'Santafé de Antioquia','code'=>'5,042'],
            ['state'=>'50','name'=>'San Carlos de Guaroa','code'=>'50,68'],
            ['state'=>'8','name'=>'Palmar de Varela','code'=>'8,52'],
            ['state'=>'5','name'=>'Santa Rosa de Osos','code'=>'5,686'],
            ['state'=>'5','name'=>'San Andrés de Cuerquía','code'=>'5,647'],
            ['state'=>'73','name'=>'Valle de San Juan','code'=>'73,854'],
            ['state'=>'68','name'=>'San Vicente de Chucurí','code'=>'68,689'],
            ['state'=>'68','name'=>'San José de Miranda','code'=>'68,684'],
            ['state'=>'88','name'=>'Providencia','code'=>'88,564'],
            ['state'=>'66','name'=>'Santa Rosa de Cabal','code'=>'66,682'],
            ['state'=>'25','name'=>'Guayabal de Siquima','code'=>'25,328'],
            ['state'=>'18','name'=>'Belén de Los Andaquies','code'=>'18,094'],
            ['state'=>'85','name'=>'Paz de Ariporo','code'=>'85,25'],
            ['state'=>'68','name'=>'Santa Helena del Opón','code'=>'68,72'],
            ['state'=>'15','name'=>'San Pablo de Borbur','code'=>'15,681'],
            ['state'=>'44','name'=>'La Jagua del Pilar','code'=>'44,42'],
            ['state'=>'20','name'=>'La Jagua de Ibirico','code'=>'20,4'],
            ['state'=>'70','name'=>'San Luis de Sincé','code'=>'70,742'],
            ['state'=>'15','name'=>'San Luis de Gaceno','code'=>'15,667'],
            ['state'=>'13','name'=>'El Carmen de Bolívar','code'=>'13,244'],
            ['state'=>'27','name'=>'El Carmen de Atrato','code'=>'27,245'],
            ['state'=>'70','name'=>'San Juan de Betulia','code'=>'70,702'],
            ['state'=>'47','name'=>'Pijiño del Carmen','code'=>'47,545'],
            ['state'=>'5','name'=>'Vigía del Fuerte','code'=>'5,873'],
            ['state'=>'13','name'=>'San Martín de Loba','code'=>'13,667'],
            ['state'=>'13','name'=>'Altos del Rosario','code'=>'13,03'],
            ['state'=>'73','name'=>'Carmen de Apicala','code'=>'73,148'],
            ['state'=>'25','name'=>'San Antonio del Tequendama','code'=>'25,645'],
            ['state'=>'68','name'=>'Sabana de Torres','code'=>'68,655'],
            ['state'=>'95','name'=>'El Retorno','code'=>'95,025'],
            ['state'=>'23','name'=>'San José de Uré','code'=>'23,682'],
            ['state'=>'52','name'=>'San Pedro de Cartago','code'=>'52,694'],
            ['state'=>'8','name'=>'Campo de La Cruz','code'=>'8,137'],
            ['state'=>'50','name'=>'San Juan de Arama','code'=>'50,683'],
            ['state'=>'5','name'=>'San José de La Montaña','code'=>'5,658'],
            ['state'=>'18','name'=>'Cartagena del Chairá','code'=>'18,15'],
            ['state'=>'27','name'=>'San José del Palmar','code'=>'27,66'],
            ['state'=>'25','name'=>'Agua de Dios','code'=>'25,001'],
            ['state'=>'13','name'=>'San Jacinto del Cauca','code'=>'13,655'],
            ['state'=>'41','name'=>'San Agustín','code'=>'41,668'],
            ['state'=>'52','name'=>'El Tablón de Gómez','code'=>'52,258'],
            ['state'=>'88','name'=>'San Andrés','code'=>'88,001'],
            ['state'=>'15','name'=>'San José de Pare','code'=>'15,664'],
            ['state'=>'86','name'=>'Valle de Guamez','code'=>'86,865'],
            ['state'=>'13','name'=>'San Pablo de Borbur','code'=>'13,67'],
            ['state'=>'70','name'=>'Santiago de Tolú','code'=>'70,82'],
            ['state'=>'11','name'=>'Bogotá D.C.','code'=>'11,001'],
            ['state'=>'25','name'=>'Carmen de Carupa','code'=>'25,154'],
            ['state'=>'23','name'=>'Ciénaga de Oro','code'=>'23,189'],
            ['state'=>'5','name'=>'San Juan de Urabá','code'=>'5,659'],
            ['state'=>'44','name'=>'San Juan del Cesar','code'=>'44,65'],
            ['state'=>'68','name'=>'El Carmen de Chucurí','code'=>'68,235'],
            ['state'=>'5','name'=>'El Carmen de Viboral','code'=>'5,148'],
            ['state'=>'66','name'=>'Belén de Umbría','code'=>'66,088'],
            ['state'=>'27','name'=>'Belén de Bajira','code'=>'27,086'],
            ['state'=>'68','name'=>'Valle de San José','code'=>'68,855'],
            ['state'=>'73','name'=>'San Luis','code'=>'73,678'],
            ['state'=>'15','name'=>'San Miguel de Sema','code'=>'15,676'],
            ['state'=>'73','name'=>'San Antonio','code'=>'73,675'],
            ['state'=>'68','name'=>'San Benito','code'=>'68,673'],
            ['state'=>'25','name'=>'Vergara','code'=>'25,862'],
            ['state'=>'23','name'=>'San Carlos','code'=>'23,678'],
            ['state'=>'91','name'=>'Puerto Alegría','code'=>'91,53'],
            ['state'=>'68','name'=>'Hato','code'=>'68,344'],
            ['state'=>'13','name'=>'San Jacinto','code'=>'13,654'],
            ['state'=>'19','name'=>'San Sebastián','code'=>'19,693'],
            ['state'=>'5','name'=>'San Carlos','code'=>'5,649'],
            ['state'=>'15','name'=>'Tuta','code'=>'15,837'],
            ['state'=>'54','name'=>'Silos','code'=>'54,743'],
            ['state'=>'54','name'=>'Cácota','code'=>'54,125'],
            ['state'=>'76','name'=>'El Dovio','code'=>'76,25'],
            ['state'=>'54','name'=>'Toledo','code'=>'54,82'],
            ['state'=>'76','name'=>'Roldanillo','code'=>'76,622'],
            ['state'=>'54','name'=>'Mutiscua','code'=>'54,48'],
            ['state'=>'76','name'=>'Argelia','code'=>'76,054'],
            ['state'=>'54','name'=>'El Zulia','code'=>'54,261'],
            ['state'=>'54','name'=>'Salazar','code'=>'54,66'],
            ['state'=>'76','name'=>'Sevilla','code'=>'76,736'],
            ['state'=>'76','name'=>'Zarzal','code'=>'76,895'],
            ['state'=>'54','name'=>'Cucutilla','code'=>'54,223'],
            ['state'=>'76','name'=>'El Cerrito','code'=>'76,248'],
            ['state'=>'76','name'=>'Cartago','code'=>'76,147'],
            ['state'=>'76','name'=>'Caicedonia','code'=>'76,122'],
            ['state'=>'54','name'=>'Puerto Santander','code'=>'54,553'],
            ['state'=>'54','name'=>'Gramalote','code'=>'54,313'],
            ['state'=>'76','name'=>'El Cairo','code'=>'76,246'],
            ['state'=>'54','name'=>'El Tarra','code'=>'54,25'],
            ['state'=>'76','name'=>'La Unión','code'=>'76,4'],
            ['state'=>'76','name'=>'Restrepo','code'=>'76,606'],
            ['state'=>'54','name'=>'Teorama','code'=>'54,8'],
            ['state'=>'76','name'=>'Dagua','code'=>'76,233'],
            ['state'=>'54','name'=>'Arboledas','code'=>'54,051'],
            ['state'=>'76','name'=>'Guacarí','code'=>'76,318'],
            ['state'=>'54','name'=>'Lourdes','code'=>'54,418'],
            ['state'=>'76','name'=>'Ansermanuevo','code'=>'76,041'],
            ['state'=>'54','name'=>'Bochalema','code'=>'54,099'],
            ['state'=>'76','name'=>'Bugalagrande','code'=>'76,113'],
            ['state'=>'54','name'=>'Convención','code'=>'54,206'],
            ['state'=>'54','name'=>'Hacarí','code'=>'54,344'],
            ['state'=>'76','name'=>'La Victoria','code'=>'76,403'],
            ['state'=>'54','name'=>'Herrán','code'=>'54,347'],
            ['state'=>'76','name'=>'Ginebra','code'=>'76,306'],
            ['state'=>'76','name'=>'Yumbo','code'=>'76,892'],
            ['state'=>'76','name'=>'Obando','code'=>'76,497'],
            ['state'=>'54','name'=>'Tibú','code'=>'54,81'],
            ['state'=>'54','name'=>'San Cayetano','code'=>'54,673'],
            ['state'=>'54','name'=>'San Calixto','code'=>'54,67'],
            ['state'=>'76','name'=>'Bolívar','code'=>'76,1'],
            ['state'=>'54','name'=>'La Playa','code'=>'54,398'],
            ['state'=>'76','name'=>'Cali','code'=>'76,001'],
            ['state'=>'76','name'=>'San Pedro','code'=>'76,67'],
            ['state'=>'76','name'=>'Guadalajara de Buga','code'=>'76,111'],
            ['state'=>'54','name'=>'Chinácota','code'=>'54,172'],
            ['state'=>'54','name'=>'Ragonvalia','code'=>'54,599'],
            ['state'=>'54','name'=>'La Esperanza','code'=>'54,385'],
            ['state'=>'54','name'=>'Villa del Rosario','code'=>'54,874'],
            ['state'=>'54','name'=>'Chitagá','code'=>'54,174'],
            ['state'=>'76','name'=>'Calima','code'=>'76,126'],
            ['state'=>'54','name'=>'Sardinata','code'=>'54,72'],
            ['state'=>'76','name'=>'Andalucía','code'=>'76,036'],
            ['state'=>'76','name'=>'Pradera','code'=>'76,563'],
            ['state'=>'54','name'=>'Abrego','code'=>'54,003'],
            ['state'=>'54','name'=>'Los Patios','code'=>'54,405'],
            ['state'=>'54','name'=>'Ocaña','code'=>'54,498'],
            ['state'=>'54','name'=>'Bucarasica','code'=>'54,109'],
            ['state'=>'76','name'=>'Yotoco','code'=>'76,89'],
            ['state'=>'76','name'=>'Palmira','code'=>'76,52'],
            ['state'=>'76','name'=>'Riofrío','code'=>'76,616'],
            ['state'=>'54','name'=>'Santiago','code'=>'54,68'],
            ['state'=>'76','name'=>'Alcalá','code'=>'76,02'],
            ['state'=>'76','name'=>'Versalles','code'=>'76,863'],
            ['state'=>'54','name'=>'Labateca','code'=>'54,377'],
            ['state'=>'54','name'=>'Cachirá','code'=>'54,128'],
            ['state'=>'54','name'=>'Villa Caro','code'=>'54,871'],
            ['state'=>'54','name'=>'Durania','code'=>'54,239'],
            ['state'=>'76','name'=>'El Águila','code'=>'76,243'],
            ['state'=>'76','name'=>'Toro','code'=>'76,823'],
            ['state'=>'76','name'=>'Candelaria','code'=>'76,13'],
            ['state'=>'76','name'=>'La Cumbre','code'=>'76,377'],
            ['state'=>'76','name'=>'Ulloa','code'=>'76,845'],
            ['state'=>'76','name'=>'Trujillo','code'=>'76,828'],
            ['state'=>'76','name'=>'Vijes','code'=>'76,869'],
            
        ];
        
        $states = State::all();      

        foreach($cities as $city){

            $city_new = new City();
            $city_new->code =str_replace(',','',$city['code']);
            $city_new->name =strtoupper($this->normalize($city['name']));
            $city_new->state_id = $states->firstWhere('code', $city['state'])->id;
            $city_new->save();
            unset($city);           
        }

    
    }

    public function normalize ($string) {
		$table = array(
			'Š'=>'S', 'š'=>'s', 'Đ'=>'Dj', 'đ'=>'dj', 'Ž'=>'Z', 'ž'=>'z', 'Č'=>'C', 'č'=>'c', 'Ć'=>'C', 'ć'=>'c',
			'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A', 'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E',
			'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I', 'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O',
			'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U', 'Ú'=>'U', 'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss',
			'à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a', 'å'=>'a', 'æ'=>'a', 'ç'=>'c', 'è'=>'e', 'é'=>'e',
			'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i', 'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o',
			'ô'=>'o', 'õ'=>'o', 'ö'=>'o', 'ø'=>'o', 'ù'=>'u', 'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'ý'=>'y', 'þ'=>'b',
			'ÿ'=>'y', 'Ŕ'=>'R', 'ŕ'=>'r',
		);
	   
		return strtr($string, $table);
	}
}
